server:
  port: 8081

spring:
  application:
    name: backend
  
  datasource:
    url: jdbc:postgresql://localhost:15432/whispr_dev
    username: whispr
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

