spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

  data:
    redis:
      url: ${REDIS_URL}

jwt:
  secret: ${JWT_SECRET}

cors:
  allowed-origins: ${FRONTEND_URL}
